name: Docs

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  docs:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: gitconfig
      run: |
        git config --global user.email automate@hanazuki.dev
        git config --global user.name automate
    - name: Generate docs
      run: scripts/generate-docs.sh
