name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false
      matrix:
        node: [10, 12, 13]
    steps:
    - uses: actions/checkout@v1
    - name: Checkout submodules
      run: |
        git submodule update --init --recursive --depth=1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Test
      run: bash ./scripts/test-packaging.sh

  lint:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: /home/runner/.dts
        key: ${{ runner.os }}-dtslint-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-dtslint-
    - name: Install
      run: npm install --no-save @types/node
    - name: Lint
      run: |
        npx dtslint --version
        npx dtslint types
