name: Test

on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-10.15]
        node: [10, 12, 13, 14]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Checkout submodules
      run: |
        git submodule update --init --recursive --depth=1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Setup GCC
      if: startsWith(matrix.os, 'macos-')
      run: |
        cd /usr/local/bin
        ln -sf gcc-9 gcc
        ln -sf g++-9 g++
    - name: Test with GCC
      run: ./scripts/test-packaging.sh
      env:
        CC: gcc
        CXX: g++
        CMAKE_BUILD_PARALLEL_LEVEL: '4'
    - name: Test with Clang
      run: ./scripts/test-packaging.sh
      env:
        CC: clang
        CXX: clang++
        CMAKE_BUILD_PARALLEL_LEVEL: '4'

  lint:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: /home/runner/.dts
        key: ${{ runner.os }}-dtslint-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-dtslint-
    - name: Install
      run: npm install --no-save "@types/node@$(node -p 'process.versions.node.split(".")[0]')"
    - name: Lint
      run: |
        npx dtslint --version
        npx dtslint types
